export default function Consciousness() {
  return (
    <main>
      <h1>Consciousness Studies</h1>

      <p>
        Consciousness is the subjective experience of awareness,
        perception, thought, emotion, and self-reflection. It remains
        one of the most challenging problems in modern science and
        philosophy.
      </p>

      <h2>Major Research Questions</h2>

      <ul>
        <li>What creates conscious experience?</li>
        <li>How does the brain generate awareness?</li>
        <li>Can consciousness emerge from computation?</li>
        <li>Is consciousness fundamental to reality?</li>
      </ul>

      <h2>Leading Theories</h2>

      <h3>Integrated Information Theory (IIT)</h3>

      <p>
        IIT proposes that consciousness corresponds to the amount of
        integrated information generated by a system.
      </p>

      <h3>Global Workspace Theory (GWT)</h3>

      <p>
        GWT suggests that consciousness arises when information becomes
        globally available throughout the brain.
      </p>

      <h3>Orchestrated Objective Reduction (Orch-OR)</h3>

      <p>
        Proposed by Roger Penrose and Stuart Hameroff, Orch-OR argues
        that quantum processes inside neuronal microtubules may play a
        role in consciousness.
      </p>

      <h2>Neuroscience of Consciousness</h2>

      <ul>
        <li>Neural Correlates of Consciousness (NCC)</li>
        <li>Brain Networks</li>
        <li>Attention and Awareness</li>
        <li>Memory Integration</li>
      </ul>

      <h2>Consciousness and Quantum Theory</h2>

      <p>
        Some speculative theories explore connections between
        consciousness and quantum mechanics, including quantum
        information processing, quantum cognition, and Orch-OR.
        These ideas remain controversial and are actively debated in
        scientific literature.
      </p>

      <h2>Future Directions</h2>

      <p>
        Future research combines neuroscience, artificial intelligence,
        cognitive science, information theory, and quantum physics to
        better understand the nature of conscious experience.
      </p>

      <h2>Key Researchers</h2>

      <ul>
        <li>Roger Penrose</li>
        <li>Stuart Hameroff</li>
        <li>Max Tegmark</li>
        <li>David Chalmers</li>
      </ul>
    </main>
  );
}